// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NyelviskolaCL.Models;

#nullable disable

namespace NyelviskolaCL.Migrations
{
    [DbContext(typeof(NyelviskolaContext))]
    [Migration("20240209142649_AddPropertiesToContextMigration")]
    partial class AddPropertiesToContextMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NyelviskolaCL.Models.Nyelv", b =>
                {
                    b.Property<long>("NyelvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Nyelvnev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NyelvId");

                    b.ToTable("Nyelvek");
                });

            modelBuilder.Entity("NyelviskolaCL.Models.Tanar", b =>
                {
                    b.Property<long>("TanarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<sbyte>("Net")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("NyelvId")
                        .HasColumnType("bigint");

                    b.Property<long>("Oradij")
                        .HasColumnType("bigint");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TanarId");

                    b.HasIndex("NyelvId");

                    b.ToTable("Tanarok");
                });

            modelBuilder.Entity("NyelviskolaCL.Models.TanitasiAlkalom", b =>
                {
                    b.Property<long>("AlkalomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Datum")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset>("Kezdesido")
                        .HasColumnType("datetime");

                    b.Property<long>("OrakSzama")
                        .HasColumnType("bigint");

                    b.Property<long>("TanarId")
                        .HasColumnType("bigint");

                    b.Property<long>("TanitvanyId")
                        .HasColumnType("bigint");

                    b.HasKey("AlkalomId");

                    b.HasIndex("TanarId");

                    b.HasIndex("TanitvanyId");

                    b.ToTable("TanitasiAlkalmak");
                });

            modelBuilder.Entity("NyelviskolaCL.Models.Tanitvany", b =>
                {
                    b.Property<long>("TanitvanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TanitvanyId");

                    b.ToTable("Tanitvanyok");
                });

            modelBuilder.Entity("NyelviskolaCL.Models.Tanar", b =>
                {
                    b.HasOne("NyelviskolaCL.Models.Nyelv", "Nyelv")
                        .WithMany("Tanarok")
                        .HasForeignKey("NyelvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nyelv");
                });

            modelBuilder.Entity("NyelviskolaCL.Models.TanitasiAlkalom", b =>
                {
                    b.HasOne("NyelviskolaCL.Models.Tanar", "Tanar")
                        .WithMany("TanitasiAlkalmak")
                        .HasForeignKey("TanarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NyelviskolaCL.Models.Tanitvany", "Tanitvany")
                        .WithMany("TanitasiAlkalmak")
                        .HasForeignKey("TanitvanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tanar");

                    b.Navigation("Tanitvany");
                });

            modelBuilder.Entity("NyelviskolaCL.Models.Nyelv", b =>
                {
                    b.Navigation("Tanarok");
                });

            modelBuilder.Entity("NyelviskolaCL.Models.Tanar", b =>
                {
                    b.Navigation("TanitasiAlkalmak");
                });

            modelBuilder.Entity("NyelviskolaCL.Models.Tanitvany", b =>
                {
                    b.Navigation("TanitasiAlkalmak");
                });
#pragma warning restore 612, 618
        }
    }
}
